"""create tables

Revision ID: 36ae250dc3c1
Revises: 
Create Date: 2023-05-21 23:16:11.688995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ae250dc3c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_table('sounds_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sound_uuid', sa.String(), nullable=True),
    sa.Column('user_id_check', sa.Integer(), nullable=True),
    sa.Column('user_uuid_check', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_check'], ['users_db.id'], ),
    sa.ForeignKeyConstraint(['user_uuid_check'], ['users_db.user_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sound_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sounds_db')
    op.drop_table('users_db')
    # ### end Alembic commands ###
